using System;
using System.Collections.Generic;
using System.Linq;
using UnityIsekaiGame.Governments;
using UnityIsekaiGame.Laws;

namespace UnityIsekaiGame.Crimes
{
    internal static class CrimeModelUtility
    {
        public static string N(string value) => PoliticalModelUtility.Normalize(value);
        public static string[] C(IEnumerable<string> values) => PoliticalModelUtility.Clean(values);
        public static bool ActiveVisibility(PoliticalVisibility visibility) => visibility != PoliticalVisibility.Hidden && visibility != PoliticalVisibility.Secret && visibility != PoliticalVisibility.DevelopmentOnly;
    }

    [Serializable] public sealed class CrimeSubjectReferenceData { public string subjectId; public string subjectType; public string role; public CrimeSubjectReferenceData Clone() => new CrimeSubjectReferenceData { subjectId = CrimeModelUtility.N(subjectId), subjectType = CrimeModelUtility.N(subjectType), role = CrimeModelUtility.N(role) }; public static CrimeSubjectReferenceData Person(string personId, string role = "") => new CrimeSubjectReferenceData { subjectId = CrimeModelUtility.N(personId), subjectType = "Person", role = CrimeModelUtility.N(role) }; }
    [Serializable] public sealed class OffenseElementEvaluationData { public OffenseElementKind kind; public string key; public string expectedValue; public string observedValue; public bool supported; public bool contradicted; public string evidenceId; public string diagnostics; public OffenseElementEvaluationData Clone() => new OffenseElementEvaluationData { kind = kind, key = CrimeModelUtility.N(key), expectedValue = CrimeModelUtility.N(expectedValue), observedValue = CrimeModelUtility.N(observedValue), supported = supported, contradicted = contradicted, evidenceId = CrimeModelUtility.N(evidenceId), diagnostics = diagnostics ?? string.Empty }; }
    [Serializable] public sealed class CrimeEvidenceLinkRecordData { public string evidenceLinkId; public string incidentId; public string reportId; public string potentialOffenseId; public string evidenceId; public EvidenceRelevance relevance; public EvidenceSufficiencyState sufficiency; public string sourceId; public double linkedWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public CrimeEvidenceLinkRecordData Clone() => new CrimeEvidenceLinkRecordData { evidenceLinkId = CrimeModelUtility.N(evidenceLinkId), incidentId = CrimeModelUtility.N(incidentId), reportId = CrimeModelUtility.N(reportId), potentialOffenseId = CrimeModelUtility.N(potentialOffenseId), evidenceId = CrimeModelUtility.N(evidenceId), relevance = relevance, sufficiency = sufficiency, sourceId = CrimeModelUtility.N(sourceId), linkedWorldTime = linkedWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }

    [Serializable] public sealed class PotentialOffenseRecordData
    {
        public string potentialOffenseId; public string incidentId; public string offenseDefinitionId; public string legalInstrumentId; public string legalProvisionId; public int legalProvisionVersion; public string[] jurisdictionIds = Array.Empty<string>(); public string[] allegedActorIds = Array.Empty<string>(); public string[] victimOrTargetIds = Array.Empty<string>(); public string[] eventIds = Array.Empty<string>(); public string placeId; public string territoryId; public double occurrenceStartWorldTime; public double occurrenceEndWorldTime; public OffenseStage stage = OffenseStage.Unknown; public ParticipationCategory participation = ParticipationCategory.Unknown; public OffenseElementEvaluationData[] elementEvaluations = Array.Empty<OffenseElementEvaluationData>(); public LegalApplicabilityStatus legalApplicabilityStatus = LegalApplicabilityStatus.Unknown; public PotentialOffenseStatus status = PotentialOffenseStatus.Unreviewed; public EvidenceSufficiencyState evidenceSufficiency = EvidenceSufficiencyState.Unknown; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public long revision = 1;
        public PotentialOffenseRecordData Clone() => new PotentialOffenseRecordData { potentialOffenseId = CrimeModelUtility.N(potentialOffenseId), incidentId = CrimeModelUtility.N(incidentId), offenseDefinitionId = CrimeModelUtility.N(offenseDefinitionId), legalInstrumentId = CrimeModelUtility.N(legalInstrumentId), legalProvisionId = CrimeModelUtility.N(legalProvisionId), legalProvisionVersion = Math.Max(0, legalProvisionVersion), jurisdictionIds = CrimeModelUtility.C(jurisdictionIds), allegedActorIds = CrimeModelUtility.C(allegedActorIds), victimOrTargetIds = CrimeModelUtility.C(victimOrTargetIds), eventIds = CrimeModelUtility.C(eventIds), placeId = CrimeModelUtility.N(placeId), territoryId = CrimeModelUtility.N(territoryId), occurrenceStartWorldTime = occurrenceStartWorldTime, occurrenceEndWorldTime = occurrenceEndWorldTime, stage = stage, participation = participation, elementEvaluations = (elementEvaluations ?? Array.Empty<OffenseElementEvaluationData>()).Select(item => item?.Clone()).Where(item => item != null).ToArray(), legalApplicabilityStatus = legalApplicabilityStatus, status = status, evidenceSufficiency = evidenceSufficiency, visibility = visibility, provenanceId = CrimeModelUtility.N(provenanceId), revision = Math.Max(1, revision) };
    }

    [Serializable] public sealed class CrimeIncidentRecordData
    {
        public string incidentId; public CrimeIncidentCategory category; public CrimeIncidentLifecycleState lifecycleState = CrimeIncidentLifecycleState.Recorded; public double occurrenceStartWorldTime; public double occurrenceEndWorldTime; public double discoveryWorldTime; public double reportingWorldTime; public string[] historicalEventIds = Array.Empty<string>(); public string primaryPlaceId; public string primaryTerritoryId; public CrimeSubjectReferenceData[] involvedSubjects = Array.Empty<CrimeSubjectReferenceData>(); public string[] potentialOffenseIds = Array.Empty<string>(); public string[] reportIds = Array.Empty<string>(); public string[] victimIds = Array.Empty<string>(); public string[] witnessIds = Array.Empty<string>(); public string[] suspectIds = Array.Empty<string>(); public string[] evidenceLinkIds = Array.Empty<string>(); public string[] jurisdictionIds = Array.Empty<string>(); public string[] relatedIncidentIds = Array.Empty<string>(); public string seriesId; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public long revision = 1;
        public CrimeIncidentRecordData Clone() => new CrimeIncidentRecordData { incidentId = CrimeModelUtility.N(incidentId), category = category, lifecycleState = lifecycleState, occurrenceStartWorldTime = occurrenceStartWorldTime, occurrenceEndWorldTime = occurrenceEndWorldTime, discoveryWorldTime = discoveryWorldTime, reportingWorldTime = reportingWorldTime, historicalEventIds = CrimeModelUtility.C(historicalEventIds), primaryPlaceId = CrimeModelUtility.N(primaryPlaceId), primaryTerritoryId = CrimeModelUtility.N(primaryTerritoryId), involvedSubjects = (involvedSubjects ?? Array.Empty<CrimeSubjectReferenceData>()).Select(item => item?.Clone()).Where(item => item != null).OrderBy(item => item.subjectType).ThenBy(item => item.subjectId, StringComparer.Ordinal).ToArray(), potentialOffenseIds = CrimeModelUtility.C(potentialOffenseIds), reportIds = CrimeModelUtility.C(reportIds), victimIds = CrimeModelUtility.C(victimIds), witnessIds = CrimeModelUtility.C(witnessIds), suspectIds = CrimeModelUtility.C(suspectIds), evidenceLinkIds = CrimeModelUtility.C(evidenceLinkIds), jurisdictionIds = CrimeModelUtility.C(jurisdictionIds), relatedIncidentIds = CrimeModelUtility.C(relatedIncidentIds), seriesId = CrimeModelUtility.N(seriesId), visibility = visibility, provenanceId = CrimeModelUtility.N(provenanceId), revision = Math.Max(1, revision) };
    }

    [Serializable] public sealed class CrimeReportRecordData { public string reportId; public string incidentId; public CrimeReportCategory category; public CrimeReportLifecycleState lifecycleState = CrimeReportLifecycleState.Submitted; public string reporterSubjectId; public string reporterSubjectType; public bool anonymous; public bool firstHand; public string sourceRumorId; public string[] allegedOffenseIds = Array.Empty<string>(); public string[] allegationIds = Array.Empty<string>(); public string[] evidenceLinkIds = Array.Empty<string>(); public double submittedWorldTime; public int reporterReliabilityBasisPoints = 5000; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public long revision = 1; public CrimeReportRecordData Clone() => new CrimeReportRecordData { reportId = CrimeModelUtility.N(reportId), incidentId = CrimeModelUtility.N(incidentId), category = category, lifecycleState = lifecycleState, reporterSubjectId = CrimeModelUtility.N(reporterSubjectId), reporterSubjectType = CrimeModelUtility.N(reporterSubjectType), anonymous = anonymous, firstHand = firstHand, sourceRumorId = CrimeModelUtility.N(sourceRumorId), allegedOffenseIds = CrimeModelUtility.C(allegedOffenseIds), allegationIds = CrimeModelUtility.C(allegationIds), evidenceLinkIds = CrimeModelUtility.C(evidenceLinkIds), submittedWorldTime = submittedWorldTime, reporterReliabilityBasisPoints = Math.Max(0, Math.Min(10000, reporterReliabilityBasisPoints)), visibility = visibility, provenanceId = CrimeModelUtility.N(provenanceId), revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class CrimeAllegationRecordData { public string allegationId; public string incidentId; public string reportId; public string potentialOffenseId; public string claimedActorId; public string claimedVictimId; public string claimedTargetId; public string conductSummary; public AllegationLifecycleState lifecycleState = AllegationLifecycleState.Recorded; public EvidenceSufficiencyState sufficiency = EvidenceSufficiencyState.Unknown; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public long revision = 1; public CrimeAllegationRecordData Clone() => new CrimeAllegationRecordData { allegationId = CrimeModelUtility.N(allegationId), incidentId = CrimeModelUtility.N(incidentId), reportId = CrimeModelUtility.N(reportId), potentialOffenseId = CrimeModelUtility.N(potentialOffenseId), claimedActorId = CrimeModelUtility.N(claimedActorId), claimedVictimId = CrimeModelUtility.N(claimedVictimId), claimedTargetId = CrimeModelUtility.N(claimedTargetId), conductSummary = conductSummary ?? string.Empty, lifecycleState = lifecycleState, sufficiency = sufficiency, visibility = visibility, provenanceId = CrimeModelUtility.N(provenanceId), revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class CrimeSuspectRecordData { public string suspectId; public string incidentId; public string potentialOffenseId; public string subjectId; public string subjectType = "Person"; public ParticipationCategory participation = ParticipationCategory.UnknownParticipant; public SuspectLifecycleState lifecycleState = SuspectLifecycleState.Suspected; public string basis; public string clearedReason; public bool misidentified; public double createdWorldTime; public double endedWorldTime = -1d; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public long revision = 1; public CrimeSuspectRecordData Clone() => new CrimeSuspectRecordData { suspectId = CrimeModelUtility.N(suspectId), incidentId = CrimeModelUtility.N(incidentId), potentialOffenseId = CrimeModelUtility.N(potentialOffenseId), subjectId = CrimeModelUtility.N(subjectId), subjectType = CrimeModelUtility.N(subjectType), participation = participation, lifecycleState = lifecycleState, basis = basis ?? string.Empty, clearedReason = clearedReason ?? string.Empty, misidentified = misidentified, createdWorldTime = createdWorldTime, endedWorldTime = endedWorldTime, visibility = visibility, provenanceId = CrimeModelUtility.N(provenanceId), revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class InvestigationRecordData { public string investigationId; public string incidentId; public string responsibleGovernmentId; public string responsibleOrganizationId; public string[] reviewerPersonIds = Array.Empty<string>(); public string[] evidenceLinkIds = Array.Empty<string>(); public CrimeIncidentLifecycleState state = CrimeIncidentLifecycleState.UnderReview; public double openedWorldTime; public double closedWorldTime = -1d; public string conclusion; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public InvestigationRecordData Clone() => new InvestigationRecordData { investigationId = CrimeModelUtility.N(investigationId), incidentId = CrimeModelUtility.N(incidentId), responsibleGovernmentId = CrimeModelUtility.N(responsibleGovernmentId), responsibleOrganizationId = CrimeModelUtility.N(responsibleOrganizationId), reviewerPersonIds = CrimeModelUtility.C(reviewerPersonIds), evidenceLinkIds = CrimeModelUtility.C(evidenceLinkIds), state = state, openedWorldTime = openedWorldTime, closedWorldTime = closedWorldTime, conclusion = conclusion ?? string.Empty, visibility = visibility, revision = Math.Max(1, revision) }; }

    [Serializable] public sealed class WarrantScopeData { public WarrantScopeKind kind; public string targetId; public string[] territoryIds = Array.Empty<string>(); public string[] jurisdictionIds = Array.Empty<string>(); public string purpose; public string exclusion; public WarrantScopeData Clone() => new WarrantScopeData { kind = kind, targetId = CrimeModelUtility.N(targetId), territoryIds = CrimeModelUtility.C(territoryIds), jurisdictionIds = CrimeModelUtility.C(jurisdictionIds), purpose = purpose ?? string.Empty, exclusion = exclusion ?? string.Empty }; }
    [Serializable] public sealed class WarrantRequestRecordData { public string warrantRequestId; public string warrantDefinitionId; public string incidentId; public string potentialOffenseId; public string requestedByPersonId; public string issuingGovernmentId; public string issuingOrganizationId; public string issuingOfficeId; public WarrantScopeData scope; public EvidenceSufficiencyState assertedThreshold = EvidenceSufficiencyState.Unknown; public WarrantRequestLifecycleState lifecycleState = WarrantRequestLifecycleState.Requested; public string reviewId; public string denialReason; public double requestedWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public WarrantRequestRecordData Clone() => new WarrantRequestRecordData { warrantRequestId = CrimeModelUtility.N(warrantRequestId), warrantDefinitionId = CrimeModelUtility.N(warrantDefinitionId), incidentId = CrimeModelUtility.N(incidentId), potentialOffenseId = CrimeModelUtility.N(potentialOffenseId), requestedByPersonId = CrimeModelUtility.N(requestedByPersonId), issuingGovernmentId = CrimeModelUtility.N(issuingGovernmentId), issuingOrganizationId = CrimeModelUtility.N(issuingOrganizationId), issuingOfficeId = CrimeModelUtility.N(issuingOfficeId), scope = scope?.Clone(), assertedThreshold = assertedThreshold, lifecycleState = lifecycleState, reviewId = CrimeModelUtility.N(reviewId), denialReason = denialReason ?? string.Empty, requestedWorldTime = requestedWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class WarrantRecordData { public string warrantId; public string warrantDefinitionId; public string warrantRequestId; public string incidentId; public string potentialOffenseId; public string issuedByPersonId; public string issuingGovernmentId; public string issuingOrganizationId; public string issuingOfficeId; public WarrantScopeData scope; public WarrantLifecycleState lifecycleState = WarrantLifecycleState.Issued; public double issuedWorldTime; public double activationWorldTime; public double expirationWorldTime = -1d; public string supersededByWarrantId; public string satisfactionRecordId; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public WarrantRecordData Clone() => new WarrantRecordData { warrantId = CrimeModelUtility.N(warrantId), warrantDefinitionId = CrimeModelUtility.N(warrantDefinitionId), warrantRequestId = CrimeModelUtility.N(warrantRequestId), incidentId = CrimeModelUtility.N(incidentId), potentialOffenseId = CrimeModelUtility.N(potentialOffenseId), issuedByPersonId = CrimeModelUtility.N(issuedByPersonId), issuingGovernmentId = CrimeModelUtility.N(issuingGovernmentId), issuingOrganizationId = CrimeModelUtility.N(issuingOrganizationId), issuingOfficeId = CrimeModelUtility.N(issuingOfficeId), scope = scope?.Clone(), lifecycleState = lifecycleState, issuedWorldTime = issuedWorldTime, activationWorldTime = activationWorldTime, expirationWorldTime = expirationWorldTime, supersededByWarrantId = CrimeModelUtility.N(supersededByWarrantId), satisfactionRecordId = CrimeModelUtility.N(satisfactionRecordId), visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class WantedStatusRecordData { public string wantedStatusId; public string wantedDefinitionId; public string warrantId; public string incidentId; public string subjectId; public string subjectType = "Person"; public string jurisdictionId; public string territoryId; public WantedPurposeCategory purpose; public WantedRiskAssessment risk = WantedRiskAssessment.Unknown; public WantedStatusLifecycleState lifecycleState = WantedStatusLifecycleState.Active; public bool derivedFromWarrant; public double activeWorldTime; public double expirationWorldTime = -1d; public string correctionReason; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public WantedStatusRecordData Clone() => new WantedStatusRecordData { wantedStatusId = CrimeModelUtility.N(wantedStatusId), wantedDefinitionId = CrimeModelUtility.N(wantedDefinitionId), warrantId = CrimeModelUtility.N(warrantId), incidentId = CrimeModelUtility.N(incidentId), subjectId = CrimeModelUtility.N(subjectId), subjectType = CrimeModelUtility.N(subjectType), jurisdictionId = CrimeModelUtility.N(jurisdictionId), territoryId = CrimeModelUtility.N(territoryId), purpose = purpose, risk = risk, lifecycleState = lifecycleState, derivedFromWarrant = derivedFromWarrant, activeWorldTime = activeWorldTime, expirationWorldTime = expirationWorldTime, correctionReason = correctionReason ?? string.Empty, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class WantedNoticeRecordData { public string noticeId; public string wantedStatusId; public string issuingGovernmentId; public string text; public bool withdrawn; public double publishedWorldTime; public double withdrawnWorldTime = -1d; public PoliticalVisibility visibility = PoliticalVisibility.Public; public long revision = 1; public WantedNoticeRecordData Clone() => new WantedNoticeRecordData { noticeId = CrimeModelUtility.N(noticeId), wantedStatusId = CrimeModelUtility.N(wantedStatusId), issuingGovernmentId = CrimeModelUtility.N(issuingGovernmentId), text = text ?? string.Empty, withdrawn = withdrawn, publishedWorldTime = publishedWorldTime, withdrawnWorldTime = withdrawnWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class CrimeTransactionRecordData { public string transactionId; public string operation; public string subjectId; public long revision; public CrimeTransactionRecordData Clone() => new CrimeTransactionRecordData { transactionId = CrimeModelUtility.N(transactionId), operation = operation ?? string.Empty, subjectId = CrimeModelUtility.N(subjectId), revision = revision }; }
    [Serializable] public sealed class CrimeRuntimeSaveData { public int schemaVersion = 1; public string worldId; public long revision; public CrimeIncidentRecordData[] incidents = Array.Empty<CrimeIncidentRecordData>(); public CrimeReportRecordData[] reports = Array.Empty<CrimeReportRecordData>(); public CrimeAllegationRecordData[] allegations = Array.Empty<CrimeAllegationRecordData>(); public CrimeSuspectRecordData[] suspects = Array.Empty<CrimeSuspectRecordData>(); public CrimeEvidenceLinkRecordData[] evidenceLinks = Array.Empty<CrimeEvidenceLinkRecordData>(); public PotentialOffenseRecordData[] potentialOffenses = Array.Empty<PotentialOffenseRecordData>(); public InvestigationRecordData[] investigations = Array.Empty<InvestigationRecordData>(); public WarrantRequestRecordData[] warrantRequests = Array.Empty<WarrantRequestRecordData>(); public WarrantRecordData[] warrants = Array.Empty<WarrantRecordData>(); public WantedStatusRecordData[] wantedStatuses = Array.Empty<WantedStatusRecordData>(); public WantedNoticeRecordData[] wantedNotices = Array.Empty<WantedNoticeRecordData>(); public CrimeTransactionRecordData[] transactions = Array.Empty<CrimeTransactionRecordData>(); public CrimeRuntimeSaveData Clone() => new CrimeRuntimeSaveData { schemaVersion = Math.Max(1, schemaVersion), worldId = CrimeModelUtility.N(worldId), revision = revision, incidents = CloneArray(incidents), reports = CloneArray(reports), allegations = CloneArray(allegations), suspects = CloneArray(suspects), evidenceLinks = CloneArray(evidenceLinks), potentialOffenses = CloneArray(potentialOffenses), investigations = CloneArray(investigations), warrantRequests = CloneArray(warrantRequests), warrants = CloneArray(warrants), wantedStatuses = CloneArray(wantedStatuses), wantedNotices = CloneArray(wantedNotices), transactions = CloneArray(transactions) }; private static T[] CloneArray<T>(IEnumerable<T> source) where T : class => (source ?? Array.Empty<T>()).Select(CloneDynamic).Where(item => item != null).ToArray(); private static T CloneDynamic<T>(T item) where T : class => item switch { CrimeIncidentRecordData value => value.Clone() as T, CrimeReportRecordData value => value.Clone() as T, CrimeAllegationRecordData value => value.Clone() as T, CrimeSuspectRecordData value => value.Clone() as T, CrimeEvidenceLinkRecordData value => value.Clone() as T, PotentialOffenseRecordData value => value.Clone() as T, InvestigationRecordData value => value.Clone() as T, WarrantRequestRecordData value => value.Clone() as T, WarrantRecordData value => value.Clone() as T, WantedStatusRecordData value => value.Clone() as T, WantedNoticeRecordData value => value.Clone() as T, CrimeTransactionRecordData value => value.Clone() as T, _ => null }; }

    public sealed class CrimeOperationResult { public bool Succeeded { get; private set; } public CrimeOperationCode Code { get; private set; } public bool Preview { get; private set; } public bool Duplicate { get; private set; } public string SubjectId { get; private set; } public string Message { get; private set; } public long RevisionBefore { get; private set; } public long RevisionAfter { get; private set; } public static CrimeOperationResult Success(string message, long before, long after, string subject = "", bool preview = false, bool duplicate = false) => new CrimeOperationResult { Succeeded = true, Code = preview ? CrimeOperationCode.Preview : duplicate ? CrimeOperationCode.Duplicate : CrimeOperationCode.Succeeded, Preview = preview, Duplicate = duplicate, SubjectId = subject ?? string.Empty, Message = message ?? string.Empty, RevisionBefore = before, RevisionAfter = after }; public static CrimeOperationResult Failure(CrimeOperationCode code, string message, long revision) => new CrimeOperationResult { Succeeded = false, Code = code, Message = message ?? string.Empty, RevisionBefore = revision, RevisionAfter = revision }; }
    public sealed class CrimeMutationEvent { public CrimeMutationEvent(string operation, string subjectId, long revision, CrimeOperationResult result) { Operation = operation ?? string.Empty; SubjectId = CrimeModelUtility.N(subjectId); Revision = revision; Result = result; } public string Operation { get; } public string SubjectId { get; } public long Revision { get; } public CrimeOperationResult Result { get; } }
    public sealed class CrimeProjectionResult<TRecord> where TRecord : class { public bool Succeeded { get; private set; } public bool Redacted { get; private set; } public TRecord Record { get; private set; } public string Message { get; private set; } public static CrimeProjectionResult<TRecord> Success(TRecord record, bool redacted, string message) => new CrimeProjectionResult<TRecord> { Succeeded = true, Redacted = redacted, Record = record, Message = message ?? string.Empty }; public static CrimeProjectionResult<TRecord> Denied(string message) => new CrimeProjectionResult<TRecord> { Message = message ?? string.Empty }; }
    public sealed class CrimeIncidentRequest { public string transactionId; public string incidentId; public CrimeIncidentCategory category; public double occurrenceStartWorldTime; public double occurrenceEndWorldTime; public double discoveryWorldTime; public double reportingWorldTime; public string[] historicalEventIds = Array.Empty<string>(); public string primaryPlaceId; public string primaryTerritoryId; public CrimeSubjectReferenceData[] involvedSubjects = Array.Empty<CrimeSubjectReferenceData>(); public string[] jurisdictionIds = Array.Empty<string>(); public string[] victimIds = Array.Empty<string>(); public string[] witnessIds = Array.Empty<string>(); public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public bool preview; }
    public sealed class CrimeReportRequest { public string transactionId; public string reportId; public string incidentId; public CrimeReportCategory category; public string reporterSubjectId; public string reporterSubjectType = "Person"; public bool anonymous; public bool firstHand; public string sourceRumorId; public double submittedWorldTime; public int reporterReliabilityBasisPoints = 5000; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public bool preview; }
    public sealed class PotentialOffenseEvaluationRequest { public string transactionId; public string potentialOffenseId; public string incidentId; public string offenseDefinitionId; public string[] allegedActorIds = Array.Empty<string>(); public string[] victimOrTargetIds = Array.Empty<string>(); public string actionId; public OffenseStage stage = OffenseStage.Completed; public ParticipationCategory participation = ParticipationCategory.PrincipalActor; public EvidenceSufficiencyState evidenceSufficiency = EvidenceSufficiencyState.Partial; public OffenseElementEvaluationData[] elementEvaluations = Array.Empty<OffenseElementEvaluationData>(); public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public bool preview; }
    public sealed class CrimeAllegationRequest { public string transactionId; public string allegationId; public string incidentId; public string reportId; public string potentialOffenseId; public string claimedActorId; public string claimedVictimId; public string claimedTargetId; public string conductSummary; public EvidenceSufficiencyState sufficiency = EvidenceSufficiencyState.Unknown; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public bool preview; }
    public sealed class CrimeSuspectRequest { public string transactionId; public string suspectId; public string incidentId; public string potentialOffenseId; public string subjectId; public string subjectType = "Person"; public ParticipationCategory participation = ParticipationCategory.UnknownParticipant; public string basis; public double worldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public bool preview; }
    public sealed class CrimeSuspectTransitionRequest { public string transactionId; public string suspectId; public SuspectLifecycleState targetState; public bool misidentified; public string reason; public double worldTime; public bool preview; }
    public sealed class CrimeEvidenceLinkRequest { public string transactionId; public string evidenceLinkId; public string incidentId; public string reportId; public string potentialOffenseId; public string evidenceId; public EvidenceRelevance relevance; public EvidenceSufficiencyState sufficiency; public string sourceId; public double worldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool preview; }
    public sealed class InvestigationRecordRequest { public string transactionId; public string investigationId; public string incidentId; public string responsibleGovernmentId; public string responsibleOrganizationId; public string[] reviewerPersonIds = Array.Empty<string>(); public double openedWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool preview; }
    public sealed class WarrantRequestCreateRequest { public string transactionId; public string warrantRequestId; public string warrantDefinitionId; public string incidentId; public string potentialOffenseId; public string requestedByPersonId; public string issuingGovernmentId; public string issuingOrganizationId; public string issuingOfficeId; public WarrantScopeData scope; public EvidenceSufficiencyState assertedThreshold = EvidenceSufficiencyState.Unknown; public double requestedWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool preview; }
    public sealed class WarrantReviewRequest { public string transactionId; public string warrantRequestId; public string reviewId; public bool approve; public string denialReason; public bool trustedSystemOperation; public bool preview; }
    public sealed class WarrantIssueRequest { public string transactionId; public string warrantId; public string warrantRequestId; public string issuedByPersonId; public double issuedWorldTime; public double activationWorldTime; public double expirationWorldTime = -1d; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool trustedSystemOperation; public bool preview; }
    public sealed class WarrantTransitionRequest { public string transactionId; public string warrantId; public WarrantLifecycleState targetState; public string supersededByWarrantId; public string satisfactionRecordId; public double worldTime; public bool preview; }
    public sealed class WantedStatusRequest { public string transactionId; public string wantedStatusId; public string wantedDefinitionId; public string warrantId; public string incidentId; public string subjectId; public string subjectType = "Person"; public string jurisdictionId; public string territoryId; public WantedRiskAssessment risk = WantedRiskAssessment.Unknown; public double activeWorldTime; public double expirationWorldTime = -1d; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool derivedFromWarrant; public bool preview; }
    public sealed class WantedStatusTransitionRequest { public string transactionId; public string wantedStatusId; public WantedStatusLifecycleState targetState; public string correctionReason; public double worldTime; public bool preview; }
    public sealed class WantedNoticeRequest { public string transactionId; public string noticeId; public string wantedStatusId; public string issuingGovernmentId; public string text; public double publishedWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Public; public bool preview; }
    public sealed class CrimeTimeEvaluationRequest { public string transactionId; public string boundaryId; public double worldTime; public int maximumOperations = 32; public bool preview; }
}
