using System;
using System.Collections.Generic;
using System.Linq;
using UnityIsekaiGame.Crimes;
using UnityIsekaiGame.Governments;

namespace UnityIsekaiGame.Justice
{
    public static class JusticeModelUtility
    {
        public static string N(string value) => PoliticalModelUtility.Normalize(value);
        public static string[] C(IEnumerable<string> values) => PoliticalModelUtility.Clean(values);
        public static bool Hidden(PoliticalVisibility visibility) => PoliticalModelUtility.IsHidden(visibility);
    }

    [Serializable] public sealed class JusticeLegalBasisData { public ArrestLegalBasisKind kind; public string warrantId; public string courtOrderId; public string sentenceId; public string authorityGrantId; public string incidentId; public string potentialOffenseId; public string legalProvisionId; public int legalProvisionVersion; public double effectiveWorldTime; public double expirationWorldTime = -1d; public string diagnostics; public JusticeLegalBasisData Clone() => new JusticeLegalBasisData { kind = kind, warrantId = JusticeModelUtility.N(warrantId), courtOrderId = JusticeModelUtility.N(courtOrderId), sentenceId = JusticeModelUtility.N(sentenceId), authorityGrantId = JusticeModelUtility.N(authorityGrantId), incidentId = JusticeModelUtility.N(incidentId), potentialOffenseId = JusticeModelUtility.N(potentialOffenseId), legalProvisionId = JusticeModelUtility.N(legalProvisionId), legalProvisionVersion = Math.Max(0, legalProvisionVersion), effectiveWorldTime = effectiveWorldTime, expirationWorldTime = expirationWorldTime, diagnostics = diagnostics ?? string.Empty }; }
    [Serializable] public sealed class JusticePartyData { public string partyId; public string personId; public string organizationId; public CasePartyRole role; public string representativePersonId; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public JusticePartyData Clone() => new JusticePartyData { partyId = JusticeModelUtility.N(partyId), personId = JusticeModelUtility.N(personId), organizationId = JusticeModelUtility.N(organizationId), role = role, representativePersonId = JusticeModelUtility.N(representativePersonId), visibility = visibility }; }
    [Serializable] public sealed class JusticeChargeOutcomeData { public string chargeId; public JudgmentOutcome outcome; public string findingId; public string reason; public JusticeChargeOutcomeData Clone() => new JusticeChargeOutcomeData { chargeId = JusticeModelUtility.N(chargeId), outcome = outcome, findingId = JusticeModelUtility.N(findingId), reason = reason ?? string.Empty }; }
    [Serializable] public sealed class SentenceComponentData { public string componentId; public SentenceCategory category; public SentenceComponentState state = SentenceComponentState.Pending; public int amount; public string currencyId; public double durationWorldTime; public string targetPersonId; public string targetOrganizationId; public string targetPropertyId; public string targetRightOrPermitId; public string destinationRuntime; public bool executed; public double startedWorldTime = -1d; public double completedWorldTime = -1d; public string executionRecordId; public string diagnostics; public SentenceComponentData Clone() => new SentenceComponentData { componentId = JusticeModelUtility.N(componentId), category = category, state = state, amount = amount, currencyId = JusticeModelUtility.N(currencyId), durationWorldTime = Math.Max(0d, durationWorldTime), targetPersonId = JusticeModelUtility.N(targetPersonId), targetOrganizationId = JusticeModelUtility.N(targetOrganizationId), targetPropertyId = JusticeModelUtility.N(targetPropertyId), targetRightOrPermitId = JusticeModelUtility.N(targetRightOrPermitId), destinationRuntime = JusticeModelUtility.N(destinationRuntime), executed = executed, startedWorldTime = startedWorldTime, completedWorldTime = completedWorldTime, executionRecordId = JusticeModelUtility.N(executionRecordId), diagnostics = diagnostics ?? string.Empty }; }

    [Serializable] public sealed class CourtRecordData { public string courtId; public string courtDefinitionId; public string justiceInstitutionDefinitionId; public string governmentId; public string organizationId; public string[] jurisdictionIds = Array.Empty<string>(); public string[] territoryIds = Array.Empty<string>(); public string courthousePlaceId; public JusticeCourtLifecycleState lifecycleState = JusticeCourtLifecycleState.Active; public double startWorldTime; public double endWorldTime = -1d; public string[] judgeOfficeIds = Array.Empty<string>(); public string[] clerkOfficeIds = Array.Empty<string>(); public string appealParentCourtId; public PoliticalVisibility visibility = PoliticalVisibility.Public; public string provenanceId; public long revision = 1; public CourtRecordData Clone() => new CourtRecordData { courtId = JusticeModelUtility.N(courtId), courtDefinitionId = JusticeModelUtility.N(courtDefinitionId), justiceInstitutionDefinitionId = JusticeModelUtility.N(justiceInstitutionDefinitionId), governmentId = JusticeModelUtility.N(governmentId), organizationId = JusticeModelUtility.N(organizationId), jurisdictionIds = JusticeModelUtility.C(jurisdictionIds), territoryIds = JusticeModelUtility.C(territoryIds), courthousePlaceId = JusticeModelUtility.N(courthousePlaceId), lifecycleState = lifecycleState, startWorldTime = startWorldTime, endWorldTime = endWorldTime, judgeOfficeIds = JusticeModelUtility.C(judgeOfficeIds), clerkOfficeIds = JusticeModelUtility.C(clerkOfficeIds), appealParentCourtId = JusticeModelUtility.N(appealParentCourtId), visibility = visibility, provenanceId = JusticeModelUtility.N(provenanceId), revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class ArrestRecordData { public string arrestId; public string arrestDefinitionId; public string arrestedPersonId; public string executingPersonId; public string executingOfficeId; public string executingOrganizationId; public string executingGovernmentId; public JusticeLegalBasisData legalBasis; public string jurisdictionId; public string territoryId; public string placeId; public bool voluntarySurrender; public string forceOutcomeId; public string custodyId; public ArrestLifecycleState lifecycleState = ArrestLifecycleState.Completed; public double arrestWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public long revision = 1; public ArrestRecordData Clone() => new ArrestRecordData { arrestId = JusticeModelUtility.N(arrestId), arrestDefinitionId = JusticeModelUtility.N(arrestDefinitionId), arrestedPersonId = JusticeModelUtility.N(arrestedPersonId), executingPersonId = JusticeModelUtility.N(executingPersonId), executingOfficeId = JusticeModelUtility.N(executingOfficeId), executingOrganizationId = JusticeModelUtility.N(executingOrganizationId), executingGovernmentId = JusticeModelUtility.N(executingGovernmentId), legalBasis = legalBasis?.Clone(), jurisdictionId = JusticeModelUtility.N(jurisdictionId), territoryId = JusticeModelUtility.N(territoryId), placeId = JusticeModelUtility.N(placeId), voluntarySurrender = voluntarySurrender, forceOutcomeId = JusticeModelUtility.N(forceOutcomeId), custodyId = JusticeModelUtility.N(custodyId), lifecycleState = lifecycleState, arrestWorldTime = arrestWorldTime, visibility = visibility, provenanceId = JusticeModelUtility.N(provenanceId), revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class CustodyRecordData { public string custodyId; public CustodyCategory category; public string personId; public string currentHolderGovernmentId; public string currentHolderOrganizationId; public string currentFacilityPlaceId; public JusticeLegalBasisData legalBasis; public string sourceArrestId; public string sourceCaseId; public string sourceSentenceId; public CustodyLifecycleState lifecycleState = CustodyLifecycleState.Active; public double startWorldTime; public double reviewDueWorldTime = -1d; public double releaseDueWorldTime = -1d; public double endWorldTime = -1d; public string releaseOrderId; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public CustodyRecordData Clone() => new CustodyRecordData { custodyId = JusticeModelUtility.N(custodyId), category = category, personId = JusticeModelUtility.N(personId), currentHolderGovernmentId = JusticeModelUtility.N(currentHolderGovernmentId), currentHolderOrganizationId = JusticeModelUtility.N(currentHolderOrganizationId), currentFacilityPlaceId = JusticeModelUtility.N(currentFacilityPlaceId), legalBasis = legalBasis?.Clone(), sourceArrestId = JusticeModelUtility.N(sourceArrestId), sourceCaseId = JusticeModelUtility.N(sourceCaseId), sourceSentenceId = JusticeModelUtility.N(sourceSentenceId), lifecycleState = lifecycleState, startWorldTime = startWorldTime, reviewDueWorldTime = reviewDueWorldTime, releaseDueWorldTime = releaseDueWorldTime, endWorldTime = endWorldTime, releaseOrderId = JusticeModelUtility.N(releaseOrderId), visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class ReleaseOrderRecordData { public string releaseOrderId; public string custodyId; public ReleaseCategory category; public string orderedByCourtId; public string orderedByAuthorityId; public string[] conditions = Array.Empty<string>(); public double orderedWorldTime; public double effectiveWorldTime; public bool executed; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public ReleaseOrderRecordData Clone() => new ReleaseOrderRecordData { releaseOrderId = JusticeModelUtility.N(releaseOrderId), custodyId = JusticeModelUtility.N(custodyId), category = category, orderedByCourtId = JusticeModelUtility.N(orderedByCourtId), orderedByAuthorityId = JusticeModelUtility.N(orderedByAuthorityId), conditions = JusticeModelUtility.C(conditions), orderedWorldTime = orderedWorldTime, effectiveWorldTime = effectiveWorldTime, executed = executed, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class ChargeRecordData { public string chargeId; public string chargeDefinitionId; public string caseId; public string defendantPersonId; public string incidentId; public string potentialOffenseId; public string offenseDefinitionId; public string legalInstrumentId; public string legalProvisionId; public int legalProvisionVersion; public EvidenceSufficiencyState filingThreshold = EvidenceSufficiencyState.Substantial; public ChargeLifecycleState lifecycleState = ChargeLifecycleState.Filed; public double filedWorldTime; public double endedWorldTime = -1d; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public ChargeRecordData Clone() => new ChargeRecordData { chargeId = JusticeModelUtility.N(chargeId), chargeDefinitionId = JusticeModelUtility.N(chargeDefinitionId), caseId = JusticeModelUtility.N(caseId), defendantPersonId = JusticeModelUtility.N(defendantPersonId), incidentId = JusticeModelUtility.N(incidentId), potentialOffenseId = JusticeModelUtility.N(potentialOffenseId), offenseDefinitionId = JusticeModelUtility.N(offenseDefinitionId), legalInstrumentId = JusticeModelUtility.N(legalInstrumentId), legalProvisionId = JusticeModelUtility.N(legalProvisionId), legalProvisionVersion = Math.Max(0, legalProvisionVersion), filingThreshold = filingThreshold, lifecycleState = lifecycleState, filedWorldTime = filedWorldTime, endedWorldTime = endedWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class CourtCaseRecordData { public string caseId; public JusticeCaseCategory category; public string courtId; public string[] incidentIds = Array.Empty<string>(); public string[] chargeIds = Array.Empty<string>(); public JusticePartyData[] parties = Array.Empty<JusticePartyData>(); public string[] hearingIds = Array.Empty<string>(); public string[] judgmentIds = Array.Empty<string>(); public CourtCaseLifecycleState lifecycleState = CourtCaseLifecycleState.Filed; public double filedWorldTime; public double closedWorldTime = -1d; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public CourtCaseRecordData Clone() => new CourtCaseRecordData { caseId = JusticeModelUtility.N(caseId), category = category, courtId = JusticeModelUtility.N(courtId), incidentIds = JusticeModelUtility.C(incidentIds), chargeIds = JusticeModelUtility.C(chargeIds), parties = (parties ?? Array.Empty<JusticePartyData>()).Select(item => item?.Clone()).Where(item => item != null).OrderBy(item => item.role).ThenBy(item => item.personId, StringComparer.Ordinal).ToArray(), hearingIds = JusticeModelUtility.C(hearingIds), judgmentIds = JusticeModelUtility.C(judgmentIds), lifecycleState = lifecycleState, filedWorldTime = filedWorldTime, closedWorldTime = closedWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class PleaRecordData { public string pleaId; public string caseId; public string chargeId; public string defendantPersonId; public PleaCategory category; public string statement; public double enteredWorldTime; public bool agreementPlaceholder; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public PleaRecordData Clone() => new PleaRecordData { pleaId = JusticeModelUtility.N(pleaId), caseId = JusticeModelUtility.N(caseId), chargeId = JusticeModelUtility.N(chargeId), defendantPersonId = JusticeModelUtility.N(defendantPersonId), category = category, statement = statement ?? string.Empty, enteredWorldTime = enteredWorldTime, agreementPlaceholder = agreementPlaceholder, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class HearingRecordData { public string hearingId; public string hearingDefinitionId; public string caseId; public HearingCategory category; public HearingLifecycleState lifecycleState = HearingLifecycleState.Scheduled; public string[] issueIds = Array.Empty<string>(); public double scheduledWorldTime; public double openedWorldTime = -1d; public double completedWorldTime = -1d; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public HearingRecordData Clone() => new HearingRecordData { hearingId = JusticeModelUtility.N(hearingId), hearingDefinitionId = JusticeModelUtility.N(hearingDefinitionId), caseId = JusticeModelUtility.N(caseId), category = category, lifecycleState = lifecycleState, issueIds = JusticeModelUtility.C(issueIds), scheduledWorldTime = scheduledWorldTime, openedWorldTime = openedWorldTime, completedWorldTime = completedWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class EvidenceSubmissionRecordData { public string evidenceSubmissionId; public string caseId; public string hearingId; public string evidenceId; public string submittedByPartyId; public EvidenceRulingState rulingState = EvidenceRulingState.Submitted; public string rulingReason; public double submittedWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public EvidenceSubmissionRecordData Clone() => new EvidenceSubmissionRecordData { evidenceSubmissionId = JusticeModelUtility.N(evidenceSubmissionId), caseId = JusticeModelUtility.N(caseId), hearingId = JusticeModelUtility.N(hearingId), evidenceId = JusticeModelUtility.N(evidenceId), submittedByPartyId = JusticeModelUtility.N(submittedByPartyId), rulingState = rulingState, rulingReason = rulingReason ?? string.Empty, submittedWorldTime = submittedWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class ProceduralRulingRecordData { public string rulingId; public string caseId; public string hearingId; public ProceduralRulingCategory category; public string subjectId; public string result; public double enteredWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public ProceduralRulingRecordData Clone() => new ProceduralRulingRecordData { rulingId = JusticeModelUtility.N(rulingId), caseId = JusticeModelUtility.N(caseId), hearingId = JusticeModelUtility.N(hearingId), category = category, subjectId = JusticeModelUtility.N(subjectId), result = result ?? string.Empty, enteredWorldTime = enteredWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class FindingRecordData { public string findingId; public string caseId; public string chargeId; public FindingCategory category; public string text; public bool proven; public double enteredWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public FindingRecordData Clone() => new FindingRecordData { findingId = JusticeModelUtility.N(findingId), caseId = JusticeModelUtility.N(caseId), chargeId = JusticeModelUtility.N(chargeId), category = category, text = text ?? string.Empty, proven = proven, enteredWorldTime = enteredWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class JudgmentRecordData { public string judgmentId; public string caseId; public string courtId; public JusticeChargeOutcomeData[] chargeOutcomes = Array.Empty<JusticeChargeOutcomeData>(); public JudgmentLifecycleState lifecycleState = JudgmentLifecycleState.Entered; public double enteredWorldTime; public double finalWorldTime = -1d; public string appealId; public PoliticalVisibility visibility = PoliticalVisibility.Public; public long revision = 1; public JudgmentRecordData Clone() => new JudgmentRecordData { judgmentId = JusticeModelUtility.N(judgmentId), caseId = JusticeModelUtility.N(caseId), courtId = JusticeModelUtility.N(courtId), chargeOutcomes = (chargeOutcomes ?? Array.Empty<JusticeChargeOutcomeData>()).Select(item => item?.Clone()).Where(item => item != null).OrderBy(item => item.chargeId, StringComparer.Ordinal).ToArray(), lifecycleState = lifecycleState, enteredWorldTime = enteredWorldTime, finalWorldTime = finalWorldTime, appealId = JusticeModelUtility.N(appealId), visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class SentenceRecordData { public string sentenceId; public string sentenceDefinitionId; public string judgmentId; public string caseId; public string defendantPersonId; public SentenceComponentData[] components = Array.Empty<SentenceComponentData>(); public SentenceLifecycleState lifecycleState = SentenceLifecycleState.Imposed; public bool concurrent; public double imposedWorldTime; public double activeWorldTime = -1d; public double completedWorldTime = -1d; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public SentenceRecordData Clone() => new SentenceRecordData { sentenceId = JusticeModelUtility.N(sentenceId), sentenceDefinitionId = JusticeModelUtility.N(sentenceDefinitionId), judgmentId = JusticeModelUtility.N(judgmentId), caseId = JusticeModelUtility.N(caseId), defendantPersonId = JusticeModelUtility.N(defendantPersonId), components = (components ?? Array.Empty<SentenceComponentData>()).Select(item => item?.Clone()).Where(item => item != null).OrderBy(item => item.componentId, StringComparer.Ordinal).ToArray(), lifecycleState = lifecycleState, concurrent = concurrent, imposedWorldTime = imposedWorldTime, activeWorldTime = activeWorldTime, completedWorldTime = completedWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class RemedyRecordData { public string remedyId; public string remedyDefinitionId; public string caseId; public string judgmentId; public RemedyCategory category; public RemedyLifecycleState lifecycleState = RemedyLifecycleState.Ordered; public string targetId; public string destinationRuntime; public double orderedWorldTime; public double completedWorldTime = -1d; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public RemedyRecordData Clone() => new RemedyRecordData { remedyId = JusticeModelUtility.N(remedyId), remedyDefinitionId = JusticeModelUtility.N(remedyDefinitionId), caseId = JusticeModelUtility.N(caseId), judgmentId = JusticeModelUtility.N(judgmentId), category = category, lifecycleState = lifecycleState, targetId = JusticeModelUtility.N(targetId), destinationRuntime = JusticeModelUtility.N(destinationRuntime), orderedWorldTime = orderedWorldTime, completedWorldTime = completedWorldTime, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class AppealRecordData { public string appealId; public string appealDefinitionId; public string sourceJudgmentId; public string appellateCourtId; public AppealLifecycleState lifecycleState = AppealLifecycleState.Filed; public AppealOutcome outcome = AppealOutcome.Unknown; public bool staysJudgment; public bool staysSentence; public double filedWorldTime; public double decidedWorldTime = -1d; public string remandCaseId; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public long revision = 1; public AppealRecordData Clone() => new AppealRecordData { appealId = JusticeModelUtility.N(appealId), appealDefinitionId = JusticeModelUtility.N(appealDefinitionId), sourceJudgmentId = JusticeModelUtility.N(sourceJudgmentId), appellateCourtId = JusticeModelUtility.N(appellateCourtId), lifecycleState = lifecycleState, outcome = outcome, staysJudgment = staysJudgment, staysSentence = staysSentence, filedWorldTime = filedWorldTime, decidedWorldTime = decidedWorldTime, remandCaseId = JusticeModelUtility.N(remandCaseId), visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class ClemencyRecordData { public string clemencyId; public string clemencyDefinitionId; public string judgmentId; public string sentenceId; public string grantorGovernmentId; public string grantorAuthorityId; public ClemencyCategory category; public ClemencyLifecycleState lifecycleState = ClemencyLifecycleState.Granted; public double grantedWorldTime; public string effectSummary; public PoliticalVisibility visibility = PoliticalVisibility.Public; public long revision = 1; public ClemencyRecordData Clone() => new ClemencyRecordData { clemencyId = JusticeModelUtility.N(clemencyId), clemencyDefinitionId = JusticeModelUtility.N(clemencyDefinitionId), judgmentId = JusticeModelUtility.N(judgmentId), sentenceId = JusticeModelUtility.N(sentenceId), grantorGovernmentId = JusticeModelUtility.N(grantorGovernmentId), grantorAuthorityId = JusticeModelUtility.N(grantorAuthorityId), category = category, lifecycleState = lifecycleState, grantedWorldTime = grantedWorldTime, effectSummary = effectSummary ?? string.Empty, visibility = visibility, revision = Math.Max(1, revision) }; }
    [Serializable] public sealed class JusticeTransactionRecordData { public string transactionId; public string operation; public string subjectId; public long revision; public JusticeTransactionRecordData Clone() => new JusticeTransactionRecordData { transactionId = JusticeModelUtility.N(transactionId), operation = operation ?? string.Empty, subjectId = JusticeModelUtility.N(subjectId), revision = revision }; }

    [Serializable]
    public sealed class JusticeRuntimeSaveData
    {
        public int schemaVersion = 1; public string worldId; public long revision;
        public CourtRecordData[] courts = Array.Empty<CourtRecordData>(); public ArrestRecordData[] arrests = Array.Empty<ArrestRecordData>(); public CustodyRecordData[] custodyRecords = Array.Empty<CustodyRecordData>(); public ReleaseOrderRecordData[] releaseOrders = Array.Empty<ReleaseOrderRecordData>(); public ChargeRecordData[] charges = Array.Empty<ChargeRecordData>(); public CourtCaseRecordData[] cases = Array.Empty<CourtCaseRecordData>(); public PleaRecordData[] pleas = Array.Empty<PleaRecordData>(); public HearingRecordData[] hearings = Array.Empty<HearingRecordData>(); public EvidenceSubmissionRecordData[] evidenceSubmissions = Array.Empty<EvidenceSubmissionRecordData>(); public ProceduralRulingRecordData[] rulings = Array.Empty<ProceduralRulingRecordData>(); public FindingRecordData[] findings = Array.Empty<FindingRecordData>(); public JudgmentRecordData[] judgments = Array.Empty<JudgmentRecordData>(); public SentenceRecordData[] sentences = Array.Empty<SentenceRecordData>(); public RemedyRecordData[] remedies = Array.Empty<RemedyRecordData>(); public AppealRecordData[] appeals = Array.Empty<AppealRecordData>(); public ClemencyRecordData[] clemencies = Array.Empty<ClemencyRecordData>(); public JusticeTransactionRecordData[] transactions = Array.Empty<JusticeTransactionRecordData>();
        public JusticeRuntimeSaveData Clone() => new JusticeRuntimeSaveData { schemaVersion = Math.Max(1, schemaVersion), worldId = JusticeModelUtility.N(worldId), revision = revision, courts = CloneArray(courts), arrests = CloneArray(arrests), custodyRecords = CloneArray(custodyRecords), releaseOrders = CloneArray(releaseOrders), charges = CloneArray(charges), cases = CloneArray(cases), pleas = CloneArray(pleas), hearings = CloneArray(hearings), evidenceSubmissions = CloneArray(evidenceSubmissions), rulings = CloneArray(rulings), findings = CloneArray(findings), judgments = CloneArray(judgments), sentences = CloneArray(sentences), remedies = CloneArray(remedies), appeals = CloneArray(appeals), clemencies = CloneArray(clemencies), transactions = CloneArray(transactions) };
        private static T[] CloneArray<T>(IEnumerable<T> source) where T : class => (source ?? Array.Empty<T>()).Select(CloneDynamic).Where(item => item != null).ToArray();
        private static T CloneDynamic<T>(T item) where T : class => item switch { CourtRecordData value => value.Clone() as T, ArrestRecordData value => value.Clone() as T, CustodyRecordData value => value.Clone() as T, ReleaseOrderRecordData value => value.Clone() as T, ChargeRecordData value => value.Clone() as T, CourtCaseRecordData value => value.Clone() as T, PleaRecordData value => value.Clone() as T, HearingRecordData value => value.Clone() as T, EvidenceSubmissionRecordData value => value.Clone() as T, ProceduralRulingRecordData value => value.Clone() as T, FindingRecordData value => value.Clone() as T, JudgmentRecordData value => value.Clone() as T, SentenceRecordData value => value.Clone() as T, RemedyRecordData value => value.Clone() as T, AppealRecordData value => value.Clone() as T, ClemencyRecordData value => value.Clone() as T, JusticeTransactionRecordData value => value.Clone() as T, _ => null };
    }

    public sealed class CourtSelectionResult { public CourtSelectionResult(IEnumerable<string> candidateCourts, IEnumerable<string> disqualifiedCourts, string primaryCourtId, IEnumerable<string> conflicts, double evaluationTime, long revision) { CandidateCourtIds = JusticeModelUtility.C(candidateCourts); DisqualifiedCourtIds = JusticeModelUtility.C(disqualifiedCourts); PrimaryCourtId = JusticeModelUtility.N(primaryCourtId); Conflicts = JusticeModelUtility.C(conflicts); EvaluationWorldTime = evaluationTime; SourceRevision = revision; } public IReadOnlyList<string> CandidateCourtIds { get; } public IReadOnlyList<string> DisqualifiedCourtIds { get; } public string PrimaryCourtId { get; } public IReadOnlyList<string> Conflicts { get; } public double EvaluationWorldTime { get; } public long SourceRevision { get; } public bool Resolved => !string.IsNullOrEmpty(PrimaryCourtId) && Conflicts.Count == 0; }
    public sealed class JusticeOperationResult { public bool Succeeded { get; private set; } public JusticeOperationCode Code { get; private set; } public bool Preview { get; private set; } public bool Duplicate { get; private set; } public string SubjectId { get; private set; } public string Message { get; private set; } public long RevisionBefore { get; private set; } public long RevisionAfter { get; private set; } public static JusticeOperationResult Success(string message, long before, long after, string subject = "", bool preview = false, bool duplicate = false) => new JusticeOperationResult { Succeeded = true, Code = preview ? JusticeOperationCode.Preview : duplicate ? JusticeOperationCode.Duplicate : JusticeOperationCode.Succeeded, Preview = preview, Duplicate = duplicate, SubjectId = subject ?? string.Empty, Message = message ?? string.Empty, RevisionBefore = before, RevisionAfter = after }; public static JusticeOperationResult Failure(JusticeOperationCode code, string message, long revision) => new JusticeOperationResult { Succeeded = false, Code = code, Message = message ?? string.Empty, RevisionBefore = revision, RevisionAfter = revision }; }
    public sealed class JusticeProjectionResult<TRecord> where TRecord : class { public bool Succeeded { get; private set; } public bool Redacted { get; private set; } public JusticeVisibilityDecision Decision { get; private set; } public TRecord Record { get; private set; } public string Message { get; private set; } public static JusticeProjectionResult<TRecord> Success(TRecord record, bool redacted, string message) => new JusticeProjectionResult<TRecord> { Succeeded = true, Redacted = redacted, Decision = redacted ? JusticeVisibilityDecision.RedactedAccess : JusticeVisibilityDecision.FullAccess, Record = record, Message = message ?? string.Empty }; public static JusticeProjectionResult<TRecord> Denied(string message, JusticeVisibilityDecision decision = JusticeVisibilityDecision.Denied) => new JusticeProjectionResult<TRecord> { Decision = decision, Message = message ?? string.Empty }; }
    public sealed class JusticeMutationEvent { public JusticeMutationEvent(string operation, string subjectId, long revision, JusticeOperationResult result) { Operation = operation ?? string.Empty; SubjectId = JusticeModelUtility.N(subjectId); Revision = revision; Result = result; } public string Operation { get; } public string SubjectId { get; } public long Revision { get; } public JusticeOperationResult Result { get; } }

    public sealed class CourtRegisterRequest { public string transactionId; public string courtId; public string courtDefinitionId; public string justiceInstitutionDefinitionId; public string governmentId; public string organizationId; public string[] jurisdictionIds = Array.Empty<string>(); public string[] territoryIds = Array.Empty<string>(); public string courthousePlaceId; public string[] judgeOfficeIds = Array.Empty<string>(); public string[] clerkOfficeIds = Array.Empty<string>(); public string appealParentCourtId; public double worldTime; public PoliticalVisibility visibility = PoliticalVisibility.Public; public string provenanceId; public bool preview; }
    public sealed class ArrestRequest { public string transactionId; public string arrestId; public string arrestDefinitionId; public string arrestedPersonId; public string executingPersonId; public string executingOfficeId; public string executingOrganizationId; public string executingGovernmentId; public JusticeLegalBasisData legalBasis; public string jurisdictionId; public string territoryId; public string placeId; public bool voluntarySurrender; public string forceOutcomeId; public string custodyId; public string custodyFacilityPlaceId; public double arrestWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public string provenanceId; public bool trustedSystemOperation; public bool preview; }
    public sealed class CustodyTransferRequest { public string transactionId; public string custodyId; public string targetHolderGovernmentId; public string targetHolderOrganizationId; public string targetFacilityPlaceId; public double worldTime; public bool preview; }
    public sealed class ReleaseOrderRequest { public string transactionId; public string releaseOrderId; public string custodyId; public ReleaseCategory category; public string orderedByCourtId; public string orderedByAuthorityId; public string[] conditions = Array.Empty<string>(); public double orderedWorldTime; public double effectiveWorldTime; public bool preview; }
    public sealed class CaseFileRequest { public string transactionId; public string caseId; public JusticeCaseCategory category; public string courtId; public string[] incidentIds = Array.Empty<string>(); public JusticePartyData[] parties = Array.Empty<JusticePartyData>(); public double filedWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool preview; }
    public sealed class ChargeFileRequest { public string transactionId; public string chargeId; public string chargeDefinitionId; public string caseId; public string defendantPersonId; public string incidentId; public string potentialOffenseId; public EvidenceSufficiencyState filingThreshold = EvidenceSufficiencyState.Substantial; public double filedWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool trustedSystemOperation; public bool preview; }
    public sealed class ChargeTransitionRequest { public string transactionId; public string chargeId; public ChargeLifecycleState targetState; public double worldTime; public bool preview; }
    public sealed class PleaRequest { public string transactionId; public string pleaId; public string caseId; public string chargeId; public string defendantPersonId; public PleaCategory category; public string statement; public double enteredWorldTime; public bool agreementPlaceholder; public bool preview; }
    public sealed class HearingScheduleRequest { public string transactionId; public string hearingId; public string hearingDefinitionId; public string caseId; public HearingCategory category; public string[] issueIds = Array.Empty<string>(); public double scheduledWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool preview; }
    public sealed class HearingTransitionRequest { public string transactionId; public string hearingId; public HearingLifecycleState targetState; public double worldTime; public bool preview; }
    public sealed class EvidenceSubmissionRequest { public string transactionId; public string evidenceSubmissionId; public string caseId; public string hearingId; public string evidenceId; public string submittedByPartyId; public double submittedWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool preview; }
    public sealed class EvidenceRulingRequest { public string transactionId; public string evidenceSubmissionId; public EvidenceRulingState targetState; public string reason; public bool preview; }
    public sealed class FindingRequest { public string transactionId; public string findingId; public string caseId; public string chargeId; public FindingCategory category; public string text; public bool proven; public double enteredWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool preview; }
    public sealed class JudgmentRequest { public string transactionId; public string judgmentId; public string caseId; public JusticeChargeOutcomeData[] chargeOutcomes = Array.Empty<JusticeChargeOutcomeData>(); public double enteredWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Public; public bool preview; }
    public sealed class SentenceRequest { public string transactionId; public string sentenceId; public string sentenceDefinitionId; public string judgmentId; public string caseId; public string defendantPersonId; public SentenceComponentData[] components = Array.Empty<SentenceComponentData>(); public bool concurrent; public double imposedWorldTime; public PoliticalVisibility visibility = PoliticalVisibility.Restricted; public bool preview; }
    public sealed class SentenceExecutionRequest { public string transactionId; public string sentenceId; public string componentId; public double worldTime; public bool preview; }
    public sealed class RemedyRequest { public string transactionId; public string remedyId; public string remedyDefinitionId; public string caseId; public string judgmentId; public RemedyCategory category; public string targetId; public string destinationRuntime; public double orderedWorldTime; public bool preview; }
    public sealed class AppealRequest { public string transactionId; public string appealId; public string appealDefinitionId; public string sourceJudgmentId; public string appellateCourtId; public bool staysJudgment; public bool staysSentence; public double filedWorldTime; public bool preview; }
    public sealed class AppealDecisionRequest { public string transactionId; public string appealId; public AppealOutcome outcome; public double decidedWorldTime; public string remandCaseId; public bool preview; }
    public sealed class ClemencyRequest { public string transactionId; public string clemencyId; public string clemencyDefinitionId; public string judgmentId; public string sentenceId; public string grantorGovernmentId; public string grantorAuthorityId; public double grantedWorldTime; public string effectSummary; public bool trustedSystemOperation; public bool preview; }
    public sealed class JusticeTimeEvaluationRequest { public string transactionId; public string boundaryId; public double worldTime; public int maximumOperations = 32; public bool preview; }
}
