namespace UnityIsekaiGame.Beings.Biology
{
    public enum BodyOperationResultCode
    {
        Success,
        PreviewSucceeded,
        DuplicateAssignment,
        MissingActorBody,
        StaleActorBody,
        MissingPerson,
        MissingSpecies,
        MissingClassification,
        MissingBodyForm,
        MissingAnatomyDefinition,
        RuntimeNotReady,
        ContributionApplicationFailure,
        TraitGrantFailure,
        CapabilityApplicationFailure,
        CalculatedStatContributionFailure,
        AnatomyConstructionFailure,
        InvalidAnatomyDefinition,
        InvalidAnatomyPresenceOverride,
        RestoreResolutionFailure,
        IncompatibleRestoredIdentity,
        InvalidSnapshotCoherence,
        InvalidConfiguration,
        InvalidRequest
    }
}
